// <auto-generated />
namespace Ostad_b5_Inv.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class script1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(script1));
        
        string IMigrationMetadata.Id
        {
            get { return "202503190344163_script1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
